# 4_sent_emails_links_from_qualtrics.R
# get the links and emails generated by Qualtrics
# used by 4_email_list.R and 6_analyse_non_response.R
# April 2024

sample = NULL

# first pilot sample, links generated on 16-Mar-2024
folder = 'emails/'
to_load = dir(folder, pattern='2024-03-16') 
for (file in to_load){ # loop through files
  this_file = paste(folder, file, sep='')
  this = read.csv(file = this_file) %>%
    clean_names() %>%
    mutate(sample_number = 1,
           email = str_remove_all(email, pattern='\\)$|;$')) # odd stuff at end not picked up previously
  sample = bind_rows(sample, this) 
}
# second pilot sample, links generated on 02-Apr-2024
folder = 'emails/second/'
to_load = dir(folder, pattern='2024-04-02')
for (file in to_load){ # loop through files
  this_file = paste(folder, file, sep='')
  this = read.csv(file = this_file) %>%
    clean_names() %>%
    mutate(sample_number = 2,
           email = str_remove_all(email, pattern='\\)$|;$')) %>% # odd stuff at end not picked up previously 
    rename('email' = 'email_address')
  sample = bind_rows(sample, this) 
}
# main (third) sample, links generated on 13-Apr-2024
folder = 'emails/third/'
to_load = dir(folder, pattern='2024-04-13')
for (file in to_load){ # loop through files
  this_file = paste(folder, file, sep='')
  this = read.csv(file = this_file) %>%
    clean_names() %>%
    mutate(sample_number = 2,
           email = str_remove_all(email, pattern='\\)$|;$'))  # odd stuff at end not picked up previously 
  sample = bind_rows(sample, this) 
}

# table(duplicated(sample$email)) # check
